language: python
python:
  - "2.7"
  - "3.6"
addons:
 apt:
   packages:
   - gcc
   - libgeoip-dev
   - libcrack2-dev
install:
  - "pip install tox"
  - "pip install -r requirements.txt"
script:
  - nosetests
  - tox
env:
  - TOXENV=py27-flake8
  - TOXENV=py27
  - TOXENV=py36-flake8
  - TOXENV=py36
